# Generated by Django 5.2 on 2026-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qualificaion', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('keyskill', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
