# Generated by Django 5.2 on 2026-07-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=15)),
                ('enquirytext', models.CharField(max_length=256)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
