# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('skill_required', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('salary', models.IntegerField()),
                ('jobtype', models.CharField(max_length=50)),
                ('lastdate', models.CharField(max_length=30)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
    ]
