# Generated by Django 5.2 on 2026-07-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('mainapp', '0003_enquiry'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applieddate', models.CharField(max_length=30)),
                ('status', models.CharField(default='Request Pending', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.jobinfo')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.jobseeker')),
            ],
        ),
    ]
